
CREATE TABLE IF NOT EXISTS axway_resources (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category text NOT NULL,
  url text NOT NULL,
  short_description text NOT NULL,
  resumo_conteudo text,
  palavras_chave text[]
);

ALTER TABLE axway_resources ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access" ON axway_resources;
CREATE POLICY "Allow public read access" ON axway_resources FOR SELECT USING (true);

INSERT INTO axway_resources (category, url, short_description, resumo_conteudo, palavras_chave) VALUES
('fase_1_products', 'https://www.axway.com/en/products/amplify-api-management-platform', 'Amplify API Platform', 'Plataforma federada de integração inteligente de dados; API Management, Fusion, Engage, AI Gateway; Leader Gartner 10x em 2025.', ARRAY['API Management', 'Federated API', 'Data Integration', 'AI Gateway', 'API Governance', 'Cloud Integration', 'API Lifecycle', 'Low-code Integration', 'API Security', 'API Monetization']),
('fase_1_products', 'https://www.axway.com/en/products/b2b-integration', 'B2B Integration', 'Integração B2B com suporte a EDI e API; VAN moderno, eInvoicing, eSubmissions, Track & Trace; Leader IDC MarketScape 2024.', ARRAY['B2B Integration', 'EDI', 'API B2B', 'VAN', 'Partner Integration', 'eInvoicing', 'Supply Chain', 'Business Network', 'Cloud B2B', 'Data Exchange']),
('fase_1_products', 'https://www.axway.com/en/products/managed-file-transfer', 'Managed File Transfer', 'MFT para 2.500+ organizações; $700 trilhões em pagamentos; 80% reservas de voos globais; SecureTransport, Transfer CFT, Workbench, MFT Cloud Services; conformidade GDPR/HIPAA/PCI-DSS.', ARRAY['Managed File Transfer', 'Secure File Transfer', 'MFT', 'SecureTransport', 'Transfer CFT', 'File Encryption', 'Compliance', 'Cloud MFT', 'Data Security', 'Business Continuity']),
('fase_1_products', 'https://www.axway.com/en/products/afah', 'Axway Financial Accounting Hub', 'Transformação digital financeira; fecha livros em 2 dias; 10M transações em 10 min; AFAH HubLedger + AFAH Model; usado por BNP Paribas.', ARRAY['Financial Accounting', 'Digital Finance', 'Subledger', 'Consolidation', 'Accounting Rules', 'ERP Integration', 'Multi-GAAP', 'Financial Compliance', 'Audit Trail', 'Data Quality']),
('fase_1_products', 'https://www.axway.com/en/products/other-products', 'Specialized Products', 'Portfólio complementar: Analytics, Automator, Sentinel, Validation Authority, Verification Router Service (farmacêutico).', ARRAY['Analytics', 'Automation', 'Sentinel', 'Monitoring', 'PKI Validation', 'Pharmaceutical Compliance', 'Real-time Intelligence', 'Data Visibility', 'Orchestration', 'Risk Management']),
('fase_2_solutions_by_industry', 'https://www.axway.com/en/solutions/automotive', 'Automotive', 'Cadeias de suprimento automotivas, integração B2B/EDI e MFT para produtores, fornecedores e logística.', ARRAY['Automotive', 'Supply Chain', 'Manufacturing', 'B2B Integration', 'Vehicle Production', 'Supplier Network', 'MFT', 'EDI', 'Cost Reduction', 'OEM']),
('fase_2_solutions_by_industry', 'https://www.axway.com/en/solutions/financial-services', 'Banking & Financial Services', '3 de 4 cartões de crédito, 6 em 10 maiores bancos globais, 40% PIB diário EUA; MFT, B2Bi, API Management, Open Banking; conformidade PCI DSS, SWIFT.', ARRAY['Banking', 'Financial Services', 'API Management', 'Open Banking', 'Payment Processing', 'PCI DSS Compliance', 'SWIFT', 'B2B Integration', 'Fintech', 'Regulatory Compliance']),
('fase_2_solutions_by_industry', 'https://www.axway.com/en/solutions/government', 'Government & Public Service', 'Entrega segura de serviços governamentais; HSPD-12, FHIR, DoD, agências civis; integração híbrida.', ARRAY['Government', 'Public Service', 'HSPD-12', 'FHIR', 'DoD Solutions', 'Federal Compliance', 'PKI Infrastructure', 'Identity Federation', 'eGovernment', 'HIPAA']),
('fase_2_solutions_by_industry', 'https://www.axway.com/en/solutions/healthcare', 'Healthcare', '2 de 3 maiores planos de saúde nacionais, 9 de 20 maiores empresas de saúde EUA; FHIR®, CMS Interoperability, Patient Access Rules.', ARRAY['Healthcare', 'FHIR', 'Patient Data', 'PHI Protection', 'Health Plans', 'CMS Interoperability', 'Patient Access', 'API Management', 'Health Exchange', 'Compliance']),
('fase_2_solutions_by_industry', 'https://www.axway.com/en/solutions/insurance', 'Insurance', 'Conformidade regulatória dinâmica, GDPR, PCI DSS; transformação digital para seguradoras.', ARRAY['Insurance', 'Digital Transformation', 'Regulatory Compliance', 'GDPR', 'PCI DSS', 'Policy Management', 'Claims Processing', 'Data Security', 'API Integration', 'Cloud Services']),
('fase_2_solutions_by_industry', 'https://www.axway.com/en/solutions/life-science', 'Life Sciences', '85% fabricantes farmacêuticos, 3 principais distribuidoras; VRS GS1, CSOS, DSCSA, Track & Trace; Novartis como cliente.', ARRAY['Pharmaceutical', 'Life Sciences', 'Drug Development', 'Supply Chain Security', 'GS1 VRS', 'CSOS', 'DSCSA Compliance', 'Track & Trace', 'Counterfeit Prevention', 'Clinical Trials']),
('fase_2_solutions_by_industry', 'https://www.axway.com/en/solutions/manufacturing-cpg', 'Manufacturing & CPG', 'Cadeias de suprimento digitais; modernização B2B com APIs; visibilidade end-to-end; análise em tempo real.', ARRAY['Manufacturing', 'CPG', 'Supply Chain', 'Digital Supply Chain', 'B2B Integration', 'ERP Systems', 'SLA Management', 'Compliance Tracking', 'API Integration', 'Cost Optimization']),
('fase_2_solutions_by_industry', 'https://www.axway.com/en/solutions/retail', 'Retail', 'Experiência omnichannel; dados POS, IoT, histórico; Track & Trace para serialização e recalls; conformidade GDPR/PCI DSS.', ARRAY['Retail', 'Customer Experience', 'POS Systems', 'Omnichannel', 'Supply Chain', 'Serialization', 'Regulatory Compliance', 'Data Analysis', 'Security', 'Digital Transformation']),
('fase_2_solutions_by_industry', 'https://www.axway.com/en/solutions/transportation-logistics', 'Transportation & Logistics', 'Rastreamento em tempo real, merge-in-transit, cross-docking; API Management + B2B/EDI + MFT; DB Schenker, Swiss Post, ATPCO como clientes.', ARRAY['Transportation', 'Logistics', 'Real-time Tracking', 'Supply Chain', 'API Integration', 'B2B/EDI', 'MFT', 'Inventory Management', 'EDI Communication', 'Global Trade']),
('fase_3_our_customers', 'https://www.axway.com/en/customers/customer-stories', 'Customer Stories', 'Mais de 11.000 empresas em todo o mundo confiam na Axway para enriquecer a experiência do cliente, acelerar a inovação e simplificar a segurança de dados e governança.', ARRAY['Customer Stories', 'Case Studies', 'Client Success', 'Digital Transformation', 'Business Results', 'Enterprise Solutions', 'Industry Leaders', 'Customer Testimonials', 'Success Metrics', 'Implementation']),
('fase_3_our_customers', 'https://www.axway.com/en/customers/advocacy-program', 'Customer Advocacy Program', 'Programa de Advocacy de Clientes que oferece oportunidades de networking e liderança intelectual para expandir presença de mercado.', ARRAY['Advocacy Program', 'Networking', 'Thought Leadership', 'Co-Marketing', 'Speaking Opportunities', 'Advisory Board', 'Executive Access', 'Brand Recognition', 'Industry Influence', 'Co-Innovation']),
('fase_3_our_customers', 'https://www.axway.com/en/2025-axway-excellence-awards', '2025 Axway Excellence Awards', 'Programa anual de prêmios reconhecendo achievement em transformação digital, inovação e excelência visionária.', ARRAY['Excellence Awards', 'Transformation Excellence', 'Innovation Excellence', 'Visionary Excellence', 'Customer Recognition', 'Digital Achievement', 'Awards Program', 'Industry Recognition', 'Case Studies', 'Summit Showcase']),
('fase_4_company', 'https://www.axway.com/en/company/about-us', 'About Us', 'Axway é uma empresa de software global que ajuda organizações a mover e integrar dados seguramente há mais de 20 anos. 1.500+ funcionários em 18 países servindo 4.000+ clientes. Líder Gartner 10x (2025).', ARRAY['About Axway', 'Company Overview', 'Global Software', 'Data Integration', 'Mission & Vision', 'Leadership', 'Employee Count', 'Revenue Growth', 'Customer Base', 'Market Position']),
('fase_4_company', 'https://www.axway.com/en/company/careers', 'Careers', 'Página de carreiras descrevendo oportunidades de emprego na Axway com valores: Better Together, Authentic, Experienced Guides, Secure.', ARRAY['Careers', 'Job Opportunities', 'Recruitment', 'Griffin Values', 'Company Culture', 'Diversity & Inclusion', 'Women in Tech', 'Global Teams', 'Professional Growth', 'Job Portal']),
('fase_4_company', 'https://www.axway.com/en/company/axway-leadership', 'Leadership', 'Equipe de liderança executiva: Roland Royer (CEO), Meetesh Patel (CPO), Ann Lloyd (CCSO), e líderes regionais e de produto.', ARRAY['Leadership', 'Executive Team', 'CEO', 'C-Suite', 'Management Team', 'Board of Directors', 'Global Leadership', 'Regional Directors', 'Product Executives', 'Executive Committee']),
('fase_4_company', 'https://www.74software.com/investor-relations', 'Investor Relations', 'Relações com investidores da 74Software (empresa mãe de Axway). Axway agora é parte de 74Software (Euronext: 74SW).', ARRAY['Investor Relations', 'Financial Information', 'Corporate Governance', 'Shareholder Information', 'Financial Reports', 'Press Releases', 'Stock Information', 'Compliance', 'Corporate Structure', 'Stakeholder Communications']),
('fase_4_company', 'https://www.axway.com/en/legal/contract-documents', 'Legal Contracts', 'Centro de contratos legais com documentação padrão: License, Subscription Services, SLAs, Support Policies, Privacy Notices, Purchase Conditions.', ARRAY['Legal Contracts', 'Terms & Conditions', 'License Agreements', 'Service Terms', 'SLAs', 'Support Policies', 'Privacy Notices', 'Product Descriptions', 'Purchase Conditions', 'Legal Documentation']),
('fase_4_company', 'https://www.axway.com/en/company/analyst-recognition', 'Analyst Recognition', 'Axway foi nomeada líder 10x na Gartner Magic Quadrant (2025). Também reconhecida como líder em IDC MarketScape (2024), Forrester Wave (2024), e G2.', ARRAY['Analyst Recognition', 'Gartner Magic Quadrant', 'IDC MarketScape', 'Forrester Wave', 'G2 Leader', 'Industry Recognition', 'Market Leadership', 'Analyst Reports', 'Third-party Validation', 'Industry Rankings']),
('fase_5_partners', 'https://www.axway.com/en/partners/find-partner', 'Find a Partner', 'Portal de busca para localizar parceiros Axway qualificados globalmente. Busca por tipo de parceiro, nível de parceria e localização geográfica. Centenas de parceiros listados.', ARRAY['Partner Search', 'Partner Directory', 'Technology Partners', 'System Integrators', 'Managed Services', 'Channel Partners', 'Partner Locator', 'Global Partners', 'Partnership Types', 'Partner Network']),
('fase_5_partners', 'https://www.axway.com/en/partners/become-partner', 'Become a Partner', 'Página de recrutamento de parceiros. Oferece 4 tipos de parcerias: Technology Alliance, Managed Services, System Integrators, Channel Partners.', ARRAY['Become Partner', 'Partner Program', 'Partnership Opportunities', 'Technology Alliance', 'Managed Services Partner', 'System Integrator', 'Channel Partner', 'Reseller Program', 'Partner Enablement', 'Partner Registration']),
('fase_5_partners', 'https://www.axway.com/en/partners/resources', 'Partner Resources', 'Hub de recursos para parceiros: Partner Portal, LinkedIn, YouTube Playlists, Axway Community para Q&A e networking.', ARRAY['Partner Resources', 'Partner Portal', 'Partner Community', 'Sales Tools', 'Partner Training', 'Deal Registration', 'Partner Network', 'Collaboration Tools', 'Partner Development', 'Knowledge Sharing']),
('fase_6_support', 'https://community.axway.com/s/', 'Axway Community', 'Comunidade online Salesforce-powered: Q&A, networking, user groups, compartilhamento de conhecimento com clientes, partners e especialistas.', ARRAY['Community', 'Q&A Forum', 'User Forum', 'Peer Networking', 'Knowledge Sharing', 'Expert Community', 'Discussion Boards', 'Problem Solving', 'Best Practices', 'User Groups']),
('fase_6_support', 'https://docs.axway.com/', 'Axway Documentation', 'Portal de documentação técnica: guias de instalação, configuração, administração, API references, best practices, troubleshooting, release notes.', ARRAY['Documentation', 'Product Guides', 'API Documentation', 'Installation Guide', 'Configuration', 'Administration', 'Technical References', 'Troubleshooting', 'Release Notes', 'Knowledge Base']),
('fase_6_support', 'https://support.axway.com/', 'Axway Support Portal', 'Portal de suporte técnico: tickets, case tracking, SLA support 24/7, patch downloads, base de conhecimento.', ARRAY['Support Portal', 'Technical Support', 'Support Tickets', 'Case Management', 'SLA Support', 'Knowledge Base', 'Patch Downloads', 'Issue Resolution', 'Help Center', 'Customer Support']),
('fase_6_support', 'https://www.axway.com/en/customers/user-groups', 'User Group Program', 'Programa de User Groups para clientes colaborarem e aprenderem. Cobre: Amplify, Automator, B2B Integration, Financial Accounting, MFT, TSIM.', ARRAY['User Groups', 'Community Groups', 'User Networking', 'Peer Learning', 'Product Education', 'User Meetings', 'Knowledge Exchange', 'Local Communities', 'Expert Access', 'User Forum']),
('fase_6_support', 'https://trust.axway.com/', 'Axway Trust Center / Security Statement', 'Trust Center: transparência em segurança, privacidade, conformidade. Compliance com GDPR, HIPAA, PCI-DSS, ISO 27001, audit reports.', ARRAY['Trust Center', 'Security', 'Compliance', 'Certifications', 'GDPR Compliance', 'Privacy Policy', 'Audit Reports', 'Security Statement', 'Data Protection', 'Risk Management']),
('fase_6_support', 'https://github.com/Axway/', 'Axway Developer Portal / GitHub', 'Repositório GitHub oficial: código aberto, SDKs, samples, ferramentas, projetos de comunidade. Centro para developer community.', ARRAY['GitHub', 'Developer Portal', 'Open Source', 'Code Samples', 'SDKs', 'Developer Resources', 'API Integration', 'Code Repository', 'Contributing', 'Developer Community']),
('fase_6_support', 'https://www.axway.com/en/resources/videos', 'Axway Videos & Webinars', 'Biblioteca de vídeos e webinars: 6 canais YouTube (Axway, Amplify, B2B, AFAH, MFT, Developer), playlists, tutorials, customer stories.', ARRAY['Videos', 'Webinars', 'YouTube', 'Product Demos', 'Tutorials', 'Customer Success Stories', 'Training Videos', 'Product Updates', 'On-Demand Webinars', 'Video Library']),
('fase_7_services', 'https://www.axway.com/en/catalysts', 'Axway Catalysts', 'Equipe de especialistas em transformação digital e APIs: Accelerate Journey program (6 workshops, 3 meses), estratégia API, programa, produto, design, DevOps, adoção.', ARRAY['Catalysts', 'Digital Transformation', 'API Strategy', 'Business Enablement', 'Accelerate Journey', 'Coaching', 'Expert Guidance', 'Enterprise Architecture', 'API-First', 'Workshops']),
('fase_7_services', 'https://www.axway.com/en/resources/training-certification', 'Training & Certification', 'Programa de treinamento através de Axway University: cursos eLearning e instructor-led para todos os produtos. Certificações para APIM, SecureTransport, Transfer CFT, B2Bi, TSIM, AFAH.', ARRAY['Training', 'Certification', 'eLearning', 'Instructor-Led', 'Axway University', 'Professional Development', 'Product Training', 'Hands-on Labs', 'Course Catalog', 'Knowledge Building']),
('fase_7_services', 'https://www.axway.com/en/services/consulting', 'Consulting Services', 'Serviços de consultoria: design de solução, arquitetura, configuração, implementação, cloud transition, health checks. Consultores com 15+ anos de experiência média.', ARRAY['Consulting', 'Professional Services', 'Solution Design', 'Implementation', 'Architecture', 'Best Practices', 'Delivery Accelerators', 'Cloud Migration', 'Solution Health Check', 'Expert Guidance']),
('fase_8_resources', 'https://resources.axway.com/', 'Resource Center', 'Hub central de recursos: case studies, white papers, webinars, guias, artigos. Organizado por produto, setores, desafios de negócio, formatos.', ARRAY['Resource Center', 'Case Studies', 'White Papers', 'Webinars', 'Guides', 'Articles', 'Data Sheets', 'eBooks', 'Solution Briefs', 'Business Resources']),
('fase_8_resources', 'https://blog.axway.com/', 'Axway Blog', 'Blog oficial Axway: notícias, trends, insights sobre integração híbrida. Seções: Learning Center, Industry Insights, Product Insights.', ARRAY['Blog', 'News', 'Trends', 'Insights', 'Hybrid Integration', 'Digital Strategy', 'Thought Leadership', 'Industry Updates', 'Technology Trends', 'Best Practices']),
('fase_8_resources', 'https://www.axway.com/en/events-and-webinars', 'Events & Webinars', 'Portal de eventos e webinars: live events, upcoming webinars, on-demand webinars por tema, setor, localização.', ARRAY['Events', 'Webinars', 'Live Events', 'Conferences', 'Workshops', 'Networking', 'On-Demand', 'Learning', 'Industry Events', 'Virtual Events']),
('fase_8_resources', 'https://university.axway.com/learn', 'Axway University', 'Plataforma de aprendizado online Axway University: cursos por produto, learning paths, certificações, labs prácticos.', ARRAY['University', 'Learning Platform', 'Online Courses', 'Learning Paths', 'Certifications', 'Practical Labs', 'Self-Paced', 'Professional Development', 'Skill Building', 'Course Completion']);
