/*
  # Create Storage Buckets for E-books
  
  1. Storage Buckets
    - `ebook-covers` - Public bucket for cover images
    - `ebook-pdfs` - Private bucket for PDF files (access via signed URLs)
  
  2. Security
    - Cover images are publicly readable
    - PDF files require authentication and signed URLs
*/

-- Create bucket for ebook cover images (public)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'ebook-covers',
  'ebook-covers',
  true,
  5242880, -- 5MB limit
  ARRAY['image/jpeg', 'image/png', 'image/webp']
)
ON CONFLICT (id) DO NOTHING;

-- Create bucket for ebook PDFs (private)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'ebook-pdfs',
  'ebook-pdfs',
  false,
  52428800, -- 50MB limit
  ARRAY['application/pdf']
)
ON CONFLICT (id) DO NOTHING;

-- Policy: Anyone can view cover images
CREATE POLICY "Public can view ebook covers"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'ebook-covers');

-- Policy: Authenticated users can upload covers (for admin)
CREATE POLICY "Authenticated users can upload ebook covers"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'ebook-covers');

-- Policy: Authenticated users can update covers
CREATE POLICY "Authenticated users can update ebook covers"
ON storage.objects FOR UPDATE
TO authenticated
USING (bucket_id = 'ebook-covers');

-- Policy: Authenticated users can delete covers
CREATE POLICY "Authenticated users can delete ebook covers"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'ebook-covers');

-- Policy: Authenticated users can manage PDFs (for admin)
CREATE POLICY "Authenticated users can upload ebook pdfs"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'ebook-pdfs');

CREATE POLICY "Authenticated users can update ebook pdfs"
ON storage.objects FOR UPDATE
TO authenticated
USING (bucket_id = 'ebook-pdfs');

CREATE POLICY "Authenticated users can delete ebook pdfs"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'ebook-pdfs');

-- Note: PDF downloads will be handled via signed URLs generated by Edge Functions
-- No public SELECT policy needed for PDFs